spring:
  application:
    name: Blog de Tecnologia
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


app:
  bootstrapping:
    superadmin:
      username: ${BOOTSTRAP_SUPERADMIN_USERNAME:superadmin}
      email: ${BOOTSTRAP_SUPERADMIN_EMAIL:superadmin@local.test}
      password: ${BOOTSTRAP_SUPERADMIN_PASSWORD:superadmin}
  jwt:
    secret: ${JWT_EXP:MWYzYzcyMThlYTc2ZDU5NDM1MTE0NWFkZDVkZmM0NjIwMzBiYzA0MzFlZGY5NGEyNzhiOGY3MGE2NzFiZjdjNg==}
    expiration: ${JWT_EXP:1800000} # 18 minutos (1000 * 60 * 18)

server:
  port: ${PORT:8080}
