spring:
  application:
    name: Blog de Tecnologia
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jwt:
    secret: "1f3c7218ea76d594351145add5dfc462030bc0431edf94a278b8f70a671bf7c6"
    expiration: 900000 # 15 minutos (1000 * 60 * 15)
    refresh_expiration: 604800000 # 7 días (1000 * 60 * 60 * 24 * 7)
    remember_expiration: 2592000000 # 30 días (1000 * 60 * 60 * 24 * 30)

server:
  port: ${PORT:8080}
