spring:
  application:
    name: Blog de Tecnologia
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: ${db_driver}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  port: ${app_port}